# Generated by Django 3.2.17 on 2023-02-03 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('age', models.CharField(blank=True, max_length=2)),
                ('genres', multiselectfield.db.fields.MultiSelectField(choices=[('ROMANCE', 'Romance'), ('COMEDY', 'Comedy'), ('FANTASY', 'Fantasy'), ('BIOGRAPHY', 'Biography'), ('TEXTBOOK', 'Text Book'), ('RECIPE', 'Recipe Book')], default=None, max_length=48)),
                ('medium', multiselectfield.db.fields.MultiSelectField(choices=[('HARDBACK', 'Hardback'), ('PAPERBACK', 'Paperback'), ('EBOOK', 'E-Book'), ('AUDIO', 'Audiobook')], default=None, max_length=30)),
                ('favourite_quote', models.TextField(blank=True)),
                ('image', models.ImageField(default='../default_profile_qdjgyp', upload_to='images/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
