# Generated by Django 4.1.6 on 2023-02-12 15:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='genres',
        ),
        migrations.AlterField(
            model_name='profile',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('HARDBACK', 'Hardback'), ('PAPERBACK', 'Paperback'), ('EBOOK', 'E-Book'), ('AUDIO', 'Audiobook')], default=None, max_length=9),
        ),
    ]
