# Generated by Django 3.2 on 2023-02-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_genres_alter_profile_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_librarian',
            field=models.BooleanField(default=False),
        ),
    ]
