# Generated by Django 3.2 on 2023-02-25 16:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_is_librarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('HARDBACK', 'Hardback'), ('PAPERBACK', 'Paperback'), ('EBOOK', 'E-Book'), ('AUDIO', 'Audiobook')], default=None, max_length=9),
        ),
    ]
