# Generated by Django 3.2.4 on 2023-03-08 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourite_quote',
        ),
    ]
