# Generated by Django 3.2.4 on 2023-03-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profile_favourite_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quote',
            field=models.TextField(blank=True),
        ),
    ]
