# Generated by Django 3.2.17 on 2023-02-09 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0005_auto_20230207_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField(max_length=500)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('book_started', models.DateField(blank=True, null=True)),
                ('book_finished', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=None)),
                ('visibility', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library.book')),
                ('tags', models.ManyToManyField(blank=True, to='library.Tags')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
