# Generated by Django 3.2.17 on 2023-02-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230210_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='book_started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
