# Generated by Django 3.2 on 2023-02-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230212_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='visibility',
        ),
        migrations.AddField(
            model_name='review',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=None, max_length=1),
        ),
    ]
