# Generated by Django 3.2 on 2023-02-27 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230226_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date_added',
        ),
    ]
